# Generated by Django 4.2.5 on 2023-10-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='annotations',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
