# Generated by Django 4.2.5 on 2023-10-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_alter_project_options_project_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
    ]
