# Generated by Django 4.2.5 on 2023-10-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_alter_project_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
